### ISSUE TITLE
[bug] Lancement des outils dev

### ISSUE THREAD

**Issue by folland87** [dataesr/react-dsfr#110]
cd example && npm i && npm start renvoi
```
The react-scripts package provided by Create React App requires a dependency:
  "webpack-dev-server": "3.11.1"
```
j'ai pareil quand je lance `npm test`

**Comment by desoindx** [comment]
Bizarre, `webpack-dev-server` est une dépendance de  `react-scripts` et devrait être installé avec.

Tu as fait un `npm install` à la racine ?

**Comment by folland87** [comment]
Chez moi les versions de "webpack-dev-server" n'étaient pas les même à la racine et dans example, d'ou l'erreur. J'ai refait un clone et npm install dans les deux et ca marche.
