### ISSUE TITLE
usage slow and buggy with v0.8

### ISSUE THREAD

**Issue by adipasquale** [dataesr/react-dsfr#214]
in my project, the PR to go from v0.7.8 to 0.8.2 is extremely large (over 3k new lines in the package-lock.json) : https://github.com/SocialGouv/enfants-du-spectacle/pull/85/files

locally it makes npm install much slower. the docker container built by our CI seems to fail because it now seems to require `python` to be installed : https://github.com/SocialGouv/enfants-du-spectacle/runs/4366278853?check_suite_focus=true

Do you have any insight on what could be happening? has something changed drastically in v0.8 ? I could not really figure it out from reading the recent commits.

Again, thank you so much for this project and please let me know how I can help

**Comment by poplingue** [comment]
Hello @adipasquale Indeed some things have changed with this new version. I'm investigating, thanks for the issue.

**Comment by poplingue** [comment]
Version 0.9.0 is published, should solve the problem.
