### ISSUE TITLE
[documentation] Icons class names have to be updated

### ISSUE THREAD

**Issue by OfficierAzarov** [dataesr/react-dsfr#227]
Current behaviour: examples given on [this page](https://dataesr.github.io/react-dsfr/#/Composants/Fondamentaux/Icons) don't work.

Fix proposal: update class names according to the new DSFR naming conventions by replacing "ri" prefix with the "fr-fi" prefix.

```
import Icon from './Icon';
import Link from '../../interface/Link';

<Link
    title="title"
    icon="ri-twitter-line"
    iconPosition="left"
    >this is a link
</Link>
```

would become

```
import Icon from './Icon';
import Link from '../../interface/Link';

<Link
    title="title"
    icon="fr-fi-twitter-line"
    iconPosition="left"
    >this is a link
</Link>
```

**Comment by poplingue** [comment]
Documentation is broken because of [styleguidist](https://react-styleguidist.js.org/)
