### ISSUE TITLE
Publication des versions et tagging sur Git

### ISSUE THREAD

**Issue by RaitoBezarius** [dataesr/react-dsfr#232]
Bonjour, merci beaucoup à nouveau pour tout le travail que vous faites.

Je remarque que la version publiée sur NPM est 1.0.3 (c.f. https://www.npmjs.com/package/@dataesr/react-dsfr) il y a un jour mais il n'y a aucun tag correspondant sur Git mise à part 1.0.0, ce qui rend difficile la compréhension de ce qui est réellement dans le paquet ou pas.

En particulier, il me semble que les Badge ne sont pas dans la version 1.0.3 bien que la publication d'hier semble être après le commit qui intègre les Badge dans l'index des composants, ainsi, il est difficile d'analyser le différentiel entre les versions.

**Comment by RaitoBezarius** [comment]
Ah, même en téléchargeant le dernier commit de ce paquet, j'obtiens les mêmes erreurs sur Badge... peut-être un problème de mon côté du coup.

**Comment by poplingue** [comment]
Bonjour @RaitoBezarius,
Merci pour ta contrib' !
Une nouvelle version est publiée avec le tag v1.0.4
