### ISSUE TITLE
TS de certains composants pas up to date

### ISSUE THREAD

**Issue by BenoitSerrano** [dataesr/react-dsfr#242]
Les composants suivants n'ont pas leur définition TS à jour par rapport à la doc et l'implémentation :
- TextInput

**Comment by kornifex** [comment]
Bonjour,

Depuis cette modification nous avons cette erreur à la validation : 

```
error TS2430: Interface 'TextInputProps' incorrectly extends interface 'InputHTMLAttributes<HTMLInputElement>'.
  Types of property 'className' are incompatible.
    Type 'TextInputClassName | undefined' is not assignable to type 'string | undefined'.
      Type 'Object' is not assignable to type 'string'.
```

A-t-on vraiment besoin du type object sur le className ?

**Comment by desoindx** [comment]
Fixed in 3.3.3
with https://github.com/dataesr/react-dsfr/pull/286
