### ISSUE TITLE
Ajout d'une class css à column pour le composant Table

### ISSUE THREAD

**Issue by CyrilBillon** [dataesr/react-dsfr#277]
Cette demande doit permettre à l'utilisateur de passer une classz CSS à la balise TD du composant Table de manière conditionnel.
Dans mon cas, on fonction du contenu de la cellule, le background doit changer de manière conditionnel.

Cordialement,

**Comment by desoindx** [comment]
Fix in 3.3.0 with https://github.com/dataesr/react-dsfr/pull/278
