### ISSUE TITLE
SSR support broken when version > 3.1.12

### ISSUE THREAD

**Issue by revolunet** [dataesr/react-dsfr#290]
Looks like some recent changes introduced some SSR-incompatible code.

I think it comes from `window` access here : https://github.com/dataesr/react-dsfr/blob/master/src/components/interface/SwitchTheme/SwitchTheme.js#L62

`window` existence could be tested before access, ex : `typeof window!=="undefined" && window.localStorage.getItem("prefers-color-scheme")`

**Comment by desoindx** [comment]
Released in version 3.4.6, don't hesitate to reopen an issue if the problem comes from another component

**Comment by revolunet** [comment]
Thanks !
