### ISSUE TITLE
Checkbox misses checked property in TypeScript

### ISSUE THREAD

**Issue by Falinor** [dataesr/react-dsfr#298]
I am trying to implement a set of checkboxes in a table. This table features a _select-all_ checkbox which, when clicked, should select all checkboxes. This behavior works as intended, although typescript is complaining about the `checked` property being missing in the type definition. It is also the case for `onClick` and some other properties.

Some [websites](https://react-typescript-cheatsheet.netlify.app/docs/advanced/patterns_by_usecase/#wrappingmirroring-a-html-element) recommend to use `React.ComponentPropsWithRef` for the following result:
```typescript
interface CheckboxProps extends ComponentPropsWithRef<'input'> {
  // Some more properties
}
```

**Before**
![Screenshot 2022-11-17 at 15 53 35](https://user-images.githubusercontent.com/9626158/202479210-7828aadb-a21f-45c7-89b4-119500390a86.png)
**After**
![Screenshot 2022-11-17 at 15 52 21](https://user-images.githubusercontent.com/9626158/202479065-d9b2f763-be43-4ae6-8d21-bc90a0f55e56.png)

I noted that no component uses this interface. Is it intended?
In a DRY attempt to reduce code repetition and serve proper types to typescript users, is there any argument against this?

Please not that I can write the PR myself if needed.

Thanks

**Comment by SophieTopart** [comment]
Hello, I am using myself several of your components in a Typescript project, and I had to manually add missing types in the index.d.ts file in my node modules react-dsfr directory... Let me know if you need to know which ones were missing, or need help updating your repo.

**Comment by SophieTopart** [comment]
By the way, I also encounter problems with icons display in tables' headers (sort function) and alerts (close button), do you have a slack community or anything else where this could be discussed?
