### ISSUE TITLE
CardDetail => set Warning Icon as a prop

### ISSUE THREAD

**Issue by Mihoub2** [dataesr/react-dsfr#304]
Hi! 
I had to use the CardDetail component but I noticed that the "fr-icon-warning-fill" cannot be easily deleted for the component. 
What about making of this icon a prop set to "false" so we can display it or not ?

Thanks!

**Comment by desoindx** [comment]
Hello ! 

Looking at the dsfr documentation, the icon is mandatory when using a `detail` => https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/carte

but you can use a regular description if you want to add text without warning icon => https://dataesr.github.io/react-dsfr/?path=/story/card--simple-card
