### ISSUE TITLE
Question / Code splitting with customs components in ToolItemGroup

### ISSUE THREAD

**Issue by sylvainlg** [dataesr/react-dsfr#306]
Hi,
I have been using the framework for a short time and have noticed some limitations.
I want to create a custom element to handle the language with its own logic (redux call) so as not to pollute the global Header component.

So i wrote : 
```ts
          <ToolItemGroup>
            <LanguageToolItem />
            <ToolItem icon="ri-user-add-line" link={getPath("/register", router.locale)}>
              {t("Toolbar.Inscription", "Inscription")}
            </ToolItem>
            <ToolItem icon="ri-user-line" link={getPath("/login", router.locale)}>
              {t("Toolbar.Connexion", "Connexion")}
            </ToolItem>
          </ToolItemGroup>
```

And the component, which provide a `ToolItem` : 

```ts
const LanguageToolItem = () => {
  const dispatch = useDispatch();
  const router = useRouter();
  const current = useSelector(currentLanguage);
  const langueCode = useSelector(currentLanguageCode);

  return (
    <ToolItem icon="ri-user-add-line" onClick={toggleLanguageModal}>
      <i className={`flag-icon flag-icon-${langueCode}`} title={langueCode} id={langueCode} />
      {current ? current.langueLoc : "Langue"}
    </ToolItem>
  );
};

export default LanguageToolItem;
```

But according to https://github.com/dataesr/react-dsfr/blob/master/src/components/interface/Header/ToolItemGroup.js#L17-L23 this is not allowed.
What is your recommendation in this case? Is it possible to remove this limitation?

**Comment by desoindx** [comment]
Hello Sylvain,

We never thought about this usecase... 
I see two solutions that you can try => 

- Take out the <ToolItem /> Container of your `LanguageToolItem` component and embed it in the `ToolGroup` => a little less maintainable but should work
- Add a `__TYPE` props to your `LanguageToolItem` that is always equal to `ToolItem` (see https://github.com/dataesr/react-dsfr/blob/39ffe7e9ec964c67509efe9ddc42c7d1487b3a25/src/components/interface/Header/ToolItem.js#L68)

Tell me if it's working

**Comment by sylvainlg** [comment]
Thank you for the quick reply

I just want to avoid the first solution.

The second works well with :

```ts
LanguageToolItem.defaultProps = {
  __TYPE: "ToolItem"
};
```

👍
