### ISSUE TITLE
Hook for ConsentManager ?

### ISSUE THREAD

**Issue by sylvainlg** [dataesr/react-dsfr#321]
Hi,

What do you think of integrating a context and a hook that allow basic consent management with the ConsentManager?

This hook would make it possible to manage the display of the banner and the consent mode, manage the recording of consents in a cookie and would provide a minimal API to manage the services: eg do I have the right to activate Youtube videos (and their cookies)

**Comment by sylvainlg** [comment]
This is link to #319

**Comment by desoindx** [comment]
release in 3.5.0
